# Generated by Django 2.0 on 2019-08-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
