# Generated by Django 2.2.3 on 2019-08-15 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legalfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
