# Generated by Django 2.0 on 2019-07-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txt',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
