# Generated by Django 2.2.4 on 2019-08-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalfiles', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='txt',
            name='tags',
            field=models.ManyToManyField(blank=True, to='legalfiles.Tag'),
        ),
    ]
