# Generated by Django 2.2.3 on 2019-08-15 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legalfiles', '0003_txt_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txt',
            name='users',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
