# Generated by Django 2.2.3 on 2019-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legalfiles', '0004_auto_20190815_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txt',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='users',
            field=models.ManyToManyField(blank=True, to='legalfiles.Txt'),
        ),
    ]
