# Generated by Django 2.2.3 on 2019-08-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legalfiles', '0005_auto_20190815_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='users',
            new_name='txts',
        ),
    ]
